pipeline:
  build:
    image: docker.infra.tstllc.net/base/ui-base-docker:latest
    commands:
      - npm update
      - npm run build

  docker:
    image: plugins/docker
    repo: docker.infra.tstllc.net/lib/david
    tag:
      - '${DRONE_BRANCH/master/latest}'
      - '${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}'
    storage_driver: overlay

  rancher:
    image: docker.infra.tstllc.net/drone/rancher
    service: npm/david-www
    docker_image: docker.infra.tstllc.net/lib/david:${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    confirm: true
    timeout: 300
    when:
      branch: master
