build:
  image: docker.infra.tstllc.net/base/ui-base-docker:latest
  pull: true
  auth_config:
    username: drone
    password: $$DRONE_REGISTRY_PASS
    email: drone@tstllc.net
  commands:
    - npm update
    - npm run build

publish:
  docker:
    repo: lib/david
    tag:
      - '$${BRANCH/master/latest}'
      - '$$BRANCH.$$BUILD_NUMBER'
    registry: docker.infra.tstllc.net
    username: drone
    password: $$DRONE_REGISTRY_PASS
    email: drone@tstllc.net
    storage_driver: overlay

cache:
  mount:
    - node_modules