coverage:
  environment:
    PORT: '3000'
    STORAGE_DIR: /storage/
    UPLOAD_DIR: /uploads/
  labels:
    io.rancher.container.pull_image: always
  image: docker.infra.tstllc.net/drone/coverage-service:master.5
  volumes:
  - /nfs/npm/coverage-service/uploads/:/uploads/:rw
  - /nfs/npm/coverage-service/storage/:/storage/:rw
david-www:
  labels:
    io.rancher.container.pull_image: always
  image: docker.infra.tstllc.net/lib/david:master.4
  volumes:
  - /nfs/npm/config/david.js:/ui/config.js:ro
npm:
  labels:
    io.rancher.container.pull_image: always
  image: keyvanfatehi/sinopia:latest
  volumes:
  - /nfs/npm/storage:/npm/storage:rw
  - /nfs/npm/htpasswd:/npm/htpasswd:rw
  - /nfs/npm/config/default.yaml:/opt/sinopia/config.yaml:ro