coverage:
  scale: 1
david-www:
  scale: 1
  health_check:
    port: 1337
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
npm:
  scale: 1
  health_check:
    port: 4873
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 5000